# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import action_decider_service_pb2 as action__decider__service__pb2


class ACServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ActionDecider = channel.unary_unary(
                '/action.decider.v1.ACService/ActionDecider',
                request_serializer=action__decider__service__pb2.DialogState.SerializeToString,
                response_deserializer=action__decider__service__pb2.ActionResponse.FromString,
                )


class ACServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ActionDecider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ACServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ActionDecider': grpc.unary_unary_rpc_method_handler(
                    servicer.ActionDecider,
                    request_deserializer=action__decider__service__pb2.DialogState.FromString,
                    response_serializer=action__decider__service__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'action.decider.v1.ACService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ACService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ActionDecider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/action.decider.v1.ACService/ActionDecider',
            action__decider__service__pb2.DialogState.SerializeToString,
            action__decider__service__pb2.ActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
